### ISSUE TITLE
Fake

### ISSUE THREAD

**Issue by telase** [SxtBox/IPTV_Player#1]
you are fake too.
this moko iptv player

https://preview.codecanyon.net/item/moko-iptv-player-iptv-video-streaming-website/full_screen_preview/23227595

**Comment by SxtBox** [comment]
you are a turkish donkey, I know it's moko, copy this player, change the names of the functions and make yourself as author, brrrrrrrrrrrrrrrr internet is full idiots.

**Comment by telase** [comment]
I think the Turks treated their ancestors badly.
Maybe your ancestry comes from Turks.
Why is this racism?
What did the Turks do to you or your family?

Or does your mother have a bad memory with the Turks?
Ask your mother, is my father Turkish?

**Comment by SxtBox** [comment]
OK

**Comment by telase** [comment]
My friend, all the documents here are public.
we are replacing them.
Doesn't everyone do this?

The purpose is sharing, we don't want anyone to pay for it, our goal is just sharing.

Yes, we get some documents from someone, edit and present them.
What's wrong with that?

You wrote bad articles to me and the Turks.
Is it my fault being Turkish?
Isn't that a racist thought?
